### ISSUE TITLE
Clearing responses

### ISSUE THREAD

**Issue by Karthik-bhogi** [phet2309/Online-Voting-System-Socket-Programming#1]
Hi bro,

I am using your codes and all for my mini project and I have encountered an issue while running it. There is nothing like clearing the total data and starting counting the data again. How to do it or we should write another code for doing this  ? 

Regards,
karthik.

**Comment by phet2309** [comment]
1. Go to admFunc.py, and inside function resetAll(), remove comment for count_reset() or reset_voter_list() and/or reset_cand_list() as required. These are defined in dframe.py
2. Go to Admin.py and remove a comment on line 40 (reset.grid......)
3. Now you have a reset button on the admin home page.
